### PR TITLE
add first attempt at pcap filtering by Community ID

### PR DESCRIPTION
**Pull request by philhagen**
This PR adds a script alongside the others which allows filtering one or more input pcap file(s) to extract only packets matching a supplied Community ID string and place them into an output pcap file.

For example:

```console
% capinfos nitroba.pcap
File name:           nitroba.pcap
File type:           Wireshark/tcpdump/... - pcap
File encapsulation:  Ethernet
File timestamp precision:  microseconds (6)
Packet size limit:   file hdr: 4096 bytes
Number of packets:   95 k
File size:           56 MB
Data size:           55 MB
Capture duration:    15759.950751 seconds
First packet time:   2008-07-21 21:51:07.095278
Last packet time:    2008-07-22 02:13:47.046029
SHA256:              f783d89ee1f6862a10e34923fb16165fdcc85811036a5a3f2a79fed8f019484a
SHA1:                8244f2e91718fa8a5134a5cf5eb4bd4d62f31df4
Strict time order:   True
% community-id-pcap nitroba.pcap | awk -F\| '{print $2}' | sort | uniq | wc -l
    2866
% community-id-pcapfilter --filter '1:XtljZRUrD6CeImZUTpT6ucBulqU=' --output reduced.pcap nitroba.pcap
% capinfos reduced.pcap
File name:           reduced.pcap
File type:           Wireshark/tcpdump/... - pcap
File encapsulation:  Ethernet
File timestamp precision:  microseconds (6)
Packet size limit:   file hdr: 1500 bytes
Number of packets:   4,825
File size:           4,640 kB
Data size:           4,562 kB
Capture duration:    44.478032 seconds
First packet time:   2008-07-22 00:47:30.302409
Last packet time:    2008-07-22 00:48:14.780441
SHA256:              9f80831528b143a5bf8925e4675a19e479a0f37dba546df7daba6eb5d3af9a37
SHA1:                f8bf565868507a76b679831580b0972dd5c60138
Strict time order:   True
% community-id-pcap reduced.pcap | awk -F\| '{print $2}' | sort | uniq | wc -l
       1
```

This may also help address a need related to issue #1.

### CODE REVIEW

**Comment by mavam** [comment]
Useful!

Another way to do this using [Tenzir](https://docs.tenzir.com):

```bash
tenzir 'from /tmp/test.pcap read pcap 
        | decapsulate
        | where community_id == "1:XtljZRUrD6CeImZUTpT6ucBulqU="
        | to file /tmp/filtered.pcap write pcap'
```

I'd be curious if `tshark` has a built-in way to do the same.

**Comment by philhagen** [comment]
Thanks!  Not familiar with Tenzir but will take a look.  `tshark` can do this via the `communityid` field, but I prefer to use more fundamental (and therefore performant) tools for filtering at layers 2-4 wherever possible - ideally BPFs of course.  (Since Wireshark and `tshark` will do the full TCP reassembly and protocol parsing processes, they are much slower to filter and are RAM-limited in the size of pcaps they can handle.)
Since Community ID cannot be reversed to a BPF for use with `tcpdump`, this seems to be nearly as fast based on my initial testing.

**Comment by ckreibich** [comment]
Hi @philhagen — thanks for the contribution! I'm very happy to merge this but we'd need at least a basic test case over in the `TestCommands` class in `communityid_test.py`. Are you able to give that a go? Otherwise I can do it too since I think it's going to be relatively straightforward.

**Comment by philhagen** [comment]
Thanks, @ckreibich - I hope the above should meet the requirement.  I'm admittedly newer to writing these tests, so if there is a better way, I am certainly open to the inputs.  I've also included a small pcap file for the test, since the existing `tcp.pcap` only contained a single conversation and wouldn't provide a good test case.

**Comment by ckreibich** [comment]
Thanks Phil, merged! I added `comunity-id-pcapfilter` to the README and also to the installed scripts. I'm going to tweak CI a bit so it does the PyPI upload automatically, and will then cut a new release. Thanks again!

**Pull request merged**
